version: 0.2

env:
  shell: bash
phases:
  install:
    runtime-versions:
      nodejs: 22
      java: corretto21
    commands:
      - node -v
      - npm -v
      - npm i -g npm
  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - echo $CODEBUILD_SRC_DIR
      - env
      - node -v
      - aws --version
      - aws dynamodb batch-write-item --request-items file://dynamoDB/prepped.json

  build:
    commands:
      - cd cypress
      - npm install
      - npm test
      - cd ../karate
      - ./gradlew test --info

  post_build:
    commands:
      - pwd
      - if [ -d "$CODEBUILD_SRC_DIR/karate/build/karate-reports" ]; then aws s3 cp $CODEBUILD_SRC_DIR/karate/build/karate-reports s3://bibliotekstjenester-test-reports/karate/$CODEBUILD_BUILD_NUMBER --recursive; fi
      - if [ -d "$CODEBUILD_SRC_DIR/cypress/cypress/screenshots" ]; then aws s3 cp $CODEBUILD_SRC_DIR/cypress/cypress/screenshots s3://bibliotekstjenester-test-reports/cypress/$CODEBUILD_BUILD_NUMBER/screenshots --recursive; fi
      - if [ -d "$CODEBUILD_SRC_DIR/cypress/cypress/videos" ]; then aws s3 cp $CODEBUILD_SRC_DIR/cypress/cypress/videos s3://bibliotekstjenester-test-reports/cypress/$CODEBUILD_BUILD_NUMBER/videos --recursive; fi
      - aws s3 rm s3://contents-backend-s3-storage-test/files/ --recursive
      - aws dynamodb batch-write-item --request-items file://$CODEBUILD_SRC_DIR/dynamoDB/delete_items.json

artifacts:
  files:
    - '**/*'
  base-directory: build
  name: $(date +%Y-%m-%d)
