version: 0.2

env:
  shell: bash

phases:

  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip3 install --upgrade cfn-lint
      - pip3 install --upgrade awscli
      - pip3 install aws-sam-cli -U
      - pip3 install --upgrade pip -r Stubs/requirements.txt

  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - env
      - aws --version
      - cfn-lint -v
      - sam --version

      # Lint
      - cfn-lint # uses .cfnlintrc
      - cd Stubs

  build:
    commands:
      - echo Build started on `date`
      - ls -a
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yml

      # Lint after 'package'
      - cfn-lint packaged.yml
      - ls -a
      - mv * ..

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Files
      - ls -l

artifacts:
  files:
    - packaged.yml
    - template-configuration.json
    - resources/*.
    - stub_api/*.
